'use strict';
const $=id=>document.getElementById(id),dims=[[320,240],[640,480],[800,600],[1024,768]],defaults={radius:5,shape:0,floor:80,tolerance:10,threshold:400,enter:1,clear:5};
let bridgeState={connected:false,cameras:[],configs:{},states:{},cellStates:{}},selectedMac='',draft=null,selectedId=null,tool='select',frame=null,drag=null,lastRadius=5,view='setup',mqttEvents=[];const names=JSON.parse(localStorage.getItem('outputNames')||'{}');
function toast(m,err=false){const e=$('toast');e.textContent=m;e.className=err?'error':'';e.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display='none',4500)}
function outputId(c){return c.group||c.id}function clone(x){return JSON.parse(JSON.stringify(x))}function cam(){return bridgeState.cameras.find(c=>c.mac===selectedMac)}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function nextId(){const used=new Set(draft.cells.flatMap(c=>[c.id,c.group].filter(Boolean)));let i=1;while(used.has(i))i++;return i}
function setView(v){view=v;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==v+'-view');const t={setup:'Set up your cameras',monitor:'Monitor your layout',network:'Bridge network'}; $('page-title').textContent=t[v];if(v==='monitor')renderMonitor()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>setView(n.dataset.view));
async function scan(choose=false){try{const ps=choose&&bridge.choosePort?await bridge.choosePort():await bridge.ports(),s=$('port-select');s.innerHTML='<option value="">'+(ps.length?'Select USB port':'No permitted serial ports')+'</option>';ps.forEach(p=>{const o=document.createElement('option');o.value=p.path;o.textContent=(p.manufacturer||'USB serial')+(p.vendorId?' · VID '+p.vendorId:'');s.append(o)});if(ps.length){s.value=ps[0].path;$('port-discovery').textContent='USB device permission available. Select it and connect.';$('port-discovery').className='port-discovery found'}else{$('port-discovery').textContent='Click Choose USB device to grant this site access to the bridge.';$('port-discovery').className='port-discovery warning'}}catch(e){toast(e.message,true)}}
$('scan-ports').onclick=$('empty-scan').onclick=()=>scan(true);$('connect').onclick=async()=>{try{if(bridgeState.connected)await bridge.disconnect();else await bridge.connect($('port-select').value)}catch(e){toast(e.message,true)}};$('refresh').onclick=()=>bridge.refresh().catch(e=>toast(e.message,true));
function selectCamera(mac){selectedMac=mac;draft=clone(bridgeState.configs[mac]||{revision:0,cells:[],topics:{},settings:{resolution:0,brightness:0,contrast:0,saturation:0,vflip:0,hmirror:0}});selectedId=null;frame=null;renderShell();renderSetup();bridge.cachedFrame(mac).then(f=>f&&displayFrame(f));setView('setup')}
function renderShell(){const c=bridgeState.connected;$('connect').textContent=c?'Disconnect':'Connect bridge';$('bridge-badge').classList.toggle('online',c);$('bridge-badge').querySelector('strong').textContent=c?'Bridge connected':'Bridge offline';$('bridge-badge').querySelector('small').textContent=c?bridgeState.path:'Connect over USB';const list=$('camera-list');list.replaceChildren();bridgeState.cameras.forEach(x=>{const b=document.createElement('button');b.className='camera-item '+(x.mac===selectedMac?'active':'');b.innerHTML=`<span>▣</span><span style="flex:1"><strong>${x.mac.slice(-8)}</strong><small>${x.count} sensors · ${x.online?'Online':'Offline'}</small></span>`;b.onclick=()=>selectCamera(x.mac);list.append(b)});$('empty').hidden=!!selectedMac;$('workspace').hidden=!selectedMac;renderNetwork();renderMonitor()}
function renderSetup(){if(!draft)return;const c=cam();$('camera-title').textContent=selectedMac;$('camera-meta').textContent=`${c?.online?'Online':'Offline'} · bridge revision ${draft.revision} · ${c?.baseline?'Baseline ready':'Baseline needed'}${Number.isFinite(c?.fps)?` · ${c.fps.toFixed(1)} frames/s`:''}`;$('sensor-count').textContent=`${draft.cells.length} sensor${draft.cells.length===1?'':'s'}`;$('resolution').value=draft.settings.resolution;$('baseline-guidance').textContent=!c?.online?'Camera offline.':!c?.revision?'Save a sensor configuration before capturing a baseline.':c.remoteRevision!==c.revision?'Waiting for the camera to apply the saved configuration.':c.baseline?'Baseline ready for this revision.':'Clear the scene, then capture a new baseline.';renderSensors();renderSelection();drawOverlay()}
function renderSensors(){const l=$('sensor-list');l.replaceChildren();draft.cells.forEach(c=>{const b=document.createElement('button');b.className='sensor-row '+(c.id===selectedId?'active':'');b.innerHTML=`<span class="pill">#${c.id}</span><span class="sensor-row-info"><strong>${names[selectedMac+':'+outputId(c)]||'Area '+outputId(c)}</strong><small>${c.x}, ${c.y} · ${draft.topics?.[outputId(c)]||outputId(c)}</small></span><span class="sensor-radius">${c.radius}px</span>`;b.onclick=()=>{selectedId=c.id;renderSetup()};l.append(b)})}
function renderSelection(){const c=draft.cells.find(x=>x.id===selectedId);$('selection-empty').hidden=!!c;$('selection-fields').hidden=!c;if(!c)return;const id=outputId(c);$('output-name').value=names[selectedMac+':'+id]||'';$('topic-name').value=draft.topics?.[id]||String(id);$('topic-preview').textContent=`Publishes to …/areas/${draft.topics?.[id]||id}/state`;$('cell-x').value=c.x;$('cell-y').value=c.y;$('cell-radius').value=c.radius;$('cell-radius-value').textContent=c.radius+' px';$('cell-enter').value=c.enter;$('cell-clear').value=c.clear}
function displayFrame(f){if(f.mac!==selectedMac)return;frame=f;const a=$('frame-canvas'),o=$('overlay-canvas');a.width=o.width=f.width;a.height=o.height=f.height;const ctx=a.getContext('2d'),img=ctx.createImageData(f.width,f.height),p=new Uint8Array(f.pixels);for(let i=0;i<p.length;i++){const j=i*4;img.data[j]=img.data[j+1]=img.data[j+2]=p[i];img.data[j+3]=255}ctx.putImageData(img,0,0);a.style.display=o.style.display='block';$('preview-placeholder').style.display='none';$('frame-label').textContent=(f.cached?'Saved ':'')+'Frame '+f.frame;$('image-size').textContent=`${f.width} × ${f.height}`;$('live-sensors').disabled=false;fitFrame();drawOverlay()}
function fitFrame(){if(!frame)return;const w=$('canvas-wrap'),scale=Math.min(w.clientWidth/frame.width,w.clientHeight/frame.height,1);['frame-canvas','overlay-canvas'].forEach(id=>{const c=$(id);c.style.width=Math.floor(frame.width*scale)+'px';c.style.height=Math.floor(frame.height*scale)+'px'})}window.addEventListener('resize',fitFrame);
function drawOverlay(){if(!frame||!draft)return;const c=$('overlay-canvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);draft.cells.forEach(s=>{const state=$('live-sensors').checked?(bridgeState.cellStates[selectedMac+':'+s.id]?.value||'unknown'):'unknown';x.beginPath();x.arc(s.x,s.y,s.radius,0,Math.PI*2);x.fillStyle=$('live-sensors').checked?({clear:'#20cf9a99',occupied:'#ff5566cc',unknown:'#8c9bab88'}[state]):(s.id===selectedId?'#25d4ab70':'#28d5ac45');x.strokeStyle=s.id===selectedId?'#cafff0':'#3ee8b8';x.fill();x.stroke()})}
function point(e){const c=$('overlay-canvas'),r=c.getBoundingClientRect();return{x:Math.round((e.clientX-r.left)*c.width/r.width),y:Math.round((e.clientY-r.top)*c.height/r.height)}}function hit(p){return[...draft.cells].reverse().find(c=>Math.hypot(c.x-p.x,c.y-p.y)<=Math.max(c.radius,5))}
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===b))});const ov=$('overlay-canvas');ov.onpointerdown=e=>{if(!frame||!draft||$('live-sensors').checked)return;const p=point(e),h=hit(p);if(tool==='sensor'){const id=nextId();draft.cells.push({...defaults,id,group:0,x:p.x,y:p.y,radius:lastRadius});selectedId=id}else if(tool==='erase'&&h){draft.cells=draft.cells.filter(c=>c.id!==h.id);selectedId=null}else if(tool==='select'){selectedId=h?.id||null;if(h)drag={id:h.id,dx:h.x-p.x,dy:h.y-p.y}}else if(tool==='block'){const group=nextId(),id=nextId()+1;draft.cells.push({...defaults,id,group,x:p.x,y:p.y,radius:lastRadius});selectedId=id}renderSetup()};ov.onpointermove=e=>{if(!drag)return;const p=point(e),c=draft.cells.find(x=>x.id===drag.id);if(c){c.x=Math.max(0,Math.min(frame.width-1,p.x+drag.dx));c.y=Math.max(0,Math.min(frame.height-1,p.y+drag.dy));drawOverlay()}};ov.onpointerup=()=>{drag=null;renderSetup()};
$('radius').oninput=e=>{lastRadius=+e.target.value;$('radius-value').textContent=lastRadius+' px'};$('resolution').onchange=e=>{draft.settings.resolution=+e.target.value;renderSetup()};$('output-name').oninput=e=>{const c=draft.cells.find(x=>x.id===selectedId);if(c){names[selectedMac+':'+outputId(c)]=e.target.value;localStorage.setItem('outputNames',JSON.stringify(names));renderSensors()}};$('topic-name').onchange=e=>{const c=draft.cells.find(x=>x.id===selectedId);if(c){const v=e.target.value.trim().toLowerCase();if(!/^[a-z0-9_-]{1,32}$/.test(v))return toast('Use 1–32 lowercase letters, digits, hyphens or underscores',true);draft.topics[outputId(c)]=v;renderSetup()}};['x','y'].forEach(k=>$('cell-'+k).onchange=e=>{const c=draft.cells.find(x=>x.id===selectedId);if(c){c[k]=+e.target.value;renderSetup()}});$('cell-radius').oninput=e=>{const c=draft.cells.find(x=>x.id===selectedId);if(c){c.radius=+e.target.value;renderSetup()}};$('delete-selected').onclick=()=>{draft.cells=draft.cells.filter(c=>c.id!==selectedId);selectedId=null;renderSetup()};
$('fetch-frame').onclick=()=>bridge.frame(selectedMac).then(()=>$('frame-progress').textContent='Requesting frame…').catch(e=>toast(e.message,true));$('capture-baseline').onclick=()=>{if(confirm('Is every configured area empty?'))bridge.baseline(selectedMac).catch(e=>toast(e.message,true))};$('save').onclick=()=>bridge.save(selectedMac,clone(draft)).then(()=>toast('Configuration saved to bridge.')).catch(e=>toast(e.message,true));$('live-sensors').onchange=drawOverlay;
function renderNetwork(){const n=bridgeState.network||{};['wifi','mqtt'].forEach(k=>{const v=bridgeState.connected?(n[k]||'disconnected'):'disconnected';$(k+'-status').textContent=v[0].toUpperCase()+v.slice(1);$(k+'-status').className=v;$(k+'-detail').textContent=bridgeState.connected?(n[k+'Detail']||'No detail'):'Connect the bridge to check status'})}
$('wifi-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);bridge.wifi(d.get('ssid'),d.get('password')).catch(x=>toast(x.message,true))};$('mqtt-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);bridge.mqtt(d.get('host'),+d.get('port'),d.get('root'),d.get('user'),d.get('password')).catch(x=>toast(x.message,true))};$('forget-wifi').onclick=()=>bridge.forgetWifi().catch(e=>toast(e.message,true));$('forget-mqtt').onclick=()=>bridge.forgetMqtt().catch(e=>toast(e.message,true));$('refresh-diagnostics').onclick=()=>bridge.logs().catch(e=>toast(e.message,true));
function renderMonitor(){const root=$('monitor-cameras');root.replaceChildren();let total=0,occ=0;bridgeState.cameras.forEach(c=>{const cfg=bridgeState.configs[c.mac]||{cells:[],topics:{}};const ids=[...new Set(cfg.cells.map(outputId))];total+=ids.length;const card=document.createElement('div');card.className='monitor-card';card.innerHTML=`<strong>${c.mac}</strong>`;ids.forEach(id=>{const s=bridgeState.states[c.mac+':'+id]?.value||'unknown';if(s==='occupied')occ++;const row=document.createElement('div');row.className='state-row';row.innerHTML=`<div><strong>${names[c.mac+':'+id]||'Area '+id}</strong><small>…/areas/${cfg.topics?.[id]||id}/state</small></div><span class="state-badge ${s}">${s}</span>`;card.append(row)});root.append(card)});$('monitor-summary').textContent=`${occ} occupied / ${total} outputs`;const l=$('mqtt-list');l.innerHTML=mqttEvents.slice(0,50).map(x=>`<div class="state-row"><code>${x.topic}</code><span>${x.value}</span></div>`).join('')}
$('viewer-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);bridge.monitorSave({host:d.get('host'),port:+d.get('port'),root:d.get('root'),user:d.get('user'),password:d.get('password')})};$('viewer-forget').onclick=()=>bridge.monitorForget();
bridge.on('bridge:state',s=>{bridgeState=s;if(!selectedMac&&s.cameras.length)selectCamera(s.cameras[0].mac);else renderShell()});bridge.on('bridge:frame',displayFrame);bridge.on('bridge:progress',p=>$('frame-progress').textContent=`Receiving ${Math.round(p.received/p.total*100)}%`);bridge.on('bridge:notice',m=>toast(m));bridge.on('bridge:error',m=>toast(m,true));bridge.on('bridge:network-event',()=>renderNetwork());bridge.on('bridge:state-event',e=>{bridgeState.states[e.mac+':'+e.id]=e;renderMonitor()});bridge.on('bridge:cell-state-event',e=>{bridgeState.cellStates[e.mac+':'+e.id]=e;drawOverlay()});bridge.on('bridge:mqtt',e=>{mqttEvents.unshift(e);renderMonitor()});bridge.on('bridge:diagnostic',e=>{const l=$('diagnostic-list');if(l.querySelector('p'))l.replaceChildren();const d=document.createElement('div');d.className='state-row';d.innerHTML=`<strong>${new Date(e.at).toLocaleString()} · ${e.code}</strong><span>${e.detail}</span>`;l.prepend(d)});bridge.on('monitor:status',e=>{$('viewer-status').textContent=e.status[0].toUpperCase()+e.status.slice(1);$('viewer-detail').textContent=e.detail||'';if(e.settings){const f=$('viewer-form');['host','port','root','user'].forEach(k=>f.elements[k].value=e.settings[k]||'')}});
scan(false);setView('monitor');
