'use strict';
(() => {
  const listeners = new Map();
  const emit = (name, data) => (listeners.get(name) || []).forEach(fn => { try { fn(data); } catch(e) { console.error(e); } });
  const MAC=/^[0-9A-F]{2}(?::[0-9A-F]{2}){5}$/;
  const portsById = new Map(); let port, reader, writer, readLoop, refreshTimer, frameTimer, buffer=''; let pending=null; let queue=Promise.resolve(), requestedFrameMac='';
  const cameras=new Map(), configs=new Map(), states=new Map(), cellStates=new Map();
  let network={wifi:'disconnected',wifiDetail:'',mqtt:'disconnected',mqttDetail:'',wifiSaved:null,mqttSaved:null}; let snapshot=null;
  const health=new Map(); let monitorClient=null;
  function hex(s=''){const bytes=new TextEncoder().encode(String(s));return bytes.length?[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase():'-';}
  function portInfo(p, i){const info=p.getInfo?.()||{};const id=`webserial:${info.usbVendorId||0}:${info.usbProductId||0}:${i}`;portsById.set(id,p);return {path:id,manufacturer:info.usbVendorId===0x303a?'Espressif':'USB serial',vendorId:(info.usbVendorId||0).toString(16).padStart(4,'0'),productId:(info.usbProductId||0).toString(16).padStart(4,'0')};}
  async function listPorts(){if(!navigator.serial)throw Error('Web Serial is not supported in this browser. Use Chrome or Edge on desktop.'); const ps=await navigator.serial.getPorts();portsById.clear();return ps.map(portInfo);}
  async function choosePort(){if(!navigator.serial)throw Error('Web Serial is not supported in this browser.');const p=await navigator.serial.requestPort();const ps=await navigator.serial.getPorts();portsById.clear();const list=ps.map(portInfo);return list;}
  function state(){emit('bridge:state',{connected:!!port,path:port?'Web Serial · 115200 baud':'',cameras:[...cameras.values()],configs:Object.fromEntries(configs),states:Object.fromEntries(states),cellStates:Object.fromEntries(cellStates),network:{...network}});}
  function failPending(message){if(pending){clearTimeout(pending.timer);pending.reject(Error(message));pending=null;}}
  function clearFrameRequest(){clearTimeout(frameTimer);frameTimer=null;requestedFrameMac='';}
  function expectFrame(mac){clearFrameRequest();requestedFrameMac=mac;frameTimer=setTimeout(()=>{if(requestedFrameMac!==mac)return;clearFrameRequest();snapshot=null;emit('bridge:error',`Frame request from ${mac} timed out before a complete image arrived.`);},120000);}
  async function run(command, timeout=12000){const task=queue.catch(()=>{}).then(()=>new Promise(async(resolve,reject)=>{if(!writer)return reject(Error('Connect a bridge first'));if(!(/^[\x20-\x7E]+$/.test(command)))return reject(Error('Invalid command text'));pending={rows:[],resolve,reject,timer:setTimeout(()=>failPending(`Timed out: ${command.split(' ')[0]}`),timeout)};try{await writer.write(new TextEncoder().encode(command+'\n'));}catch(e){failPending(e.message||String(e));}}));queue=task;return task;}
  function parseRow(line){const p=line.trim().split(/\s+/);if(p[0]==='CAMERA'&&MAC.test(p[1]))return{type:'camera',mac:p[1],online:p[2]==='online',revision:+p[3],remoteRevision:+p[4],count:+p[5],baseline:p[6]==='1'};if(p[0]==='CONFIG'&&MAC.test(p[1]))return{type:'config',revision:+p[2],lastAutoSizeRevision:+p[4],settings:{resolution:+p[5],brightness:+p[6],contrast:+p[7],saturation:+p[8],vflip:+p[9],hmirror:+p[10]}};if(p[0]==='CELL')return{type:'cell',cell:{id:+p[2],group:+p[3],x:+p[4],y:+p[5],radius:+p[6],shape:+p[7],floor:+p[8],tolerance:+p[9],threshold:+p[10],enter:+p[11],clear:+p[12],createdRevision:+p[13]}};if(p[0]==='TOPIC')return{type:'topic',id:+p[1],name:p[2]};}
  function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let n=0;n<8;n++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
  function startSnapshot(p){const rawCount=+p[6],count=p[8]===undefined?rawCount:+p[8],width=+p[4],height=+p[5],codec=p[10]===undefined?0:+p[10],crc=parseInt(p[7],16)>>>0,wireCrc=p[9]===undefined?crc:(parseInt(p[9],16)>>>0);if(!MAC.test(p[2])||![[320,240],[640,480],[800,600],[1024,768]].some(([w,h])=>w===width&&h===height)||rawCount!==width*height||![0,1].includes(codec)||!Number.isInteger(count)||count<1||count>rawCount||(codec===0&&(count!==rawCount||wireCrc!==crc)))throw Error('Invalid frame header');snapshot={mac:p[2],frame:+p[3],width,height,rawCount,crc,count,wireCrc,codec,offset:0,wire:new Uint8Array(count)};emit('bridge:progress',{mac:p[2],received:0,total:count});}
  function addSnapshot(p){const offset=+p[3],hexdata=p[4]||'';if(!snapshot||p[2]!==snapshot.mac||offset!==snapshot.offset||!(/^(?:[0-9A-F]{2})+$/.test(hexdata)))throw Error('Frame chunk is out of order');const bytes=new Uint8Array(hexdata.length/2);if(offset+bytes.length>snapshot.count)throw Error('Frame exceeds declared size');for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(hexdata.slice(i*2,i*2+2),16);snapshot.wire.set(bytes,offset);snapshot.offset+=bytes.length;if(snapshot.offset%12000<bytes.length||snapshot.offset===snapshot.count)emit('bridge:progress',{mac:snapshot.mac,received:snapshot.offset,total:snapshot.count});}
  let frameDbPromise;
  function frameDb(){if(!frameDbPromise)frameDbPromise=new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('IndexedDB is unavailable'));const request=indexedDB.open('railway-camera-frames',1);request.onupgradeneeded=()=>request.result.createObjectStore('frames',{keyPath:'mac'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('Could not open frame cache'));});return frameDbPromise;}
  async function cacheFrame(frame){const db=await frameDb();await new Promise((resolve,reject)=>{const transaction=db.transaction('frames','readwrite');transaction.objectStore('frames').put(frame);transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error||Error('Could not cache frame'));});}
  async function finishSnapshot(parts){const s=snapshot;snapshot=null;if(!s||parts[2]!==s.mac||parts[3]!=='ok'||s.offset!==s.count||crc32(s.wire)!==s.wireCrc)throw Error('Frame failed transfer CRC or length check');let pixels=s.wire;if(s.codec===1){if(typeof DecompressionStream==='undefined')throw Error('Compressed frame received but this browser cannot decompress it');const ds=new DecompressionStream('deflate-raw');const ab=await new Response(new Blob([s.wire]).stream().pipeThrough(ds)).arrayBuffer();pixels=new Uint8Array(ab);}if(pixels.length!==s.rawCount||crc32(pixels)!==s.crc)throw Error('Frame failed image CRC or length check');const pixelBuffer=pixels.buffer.slice(pixels.byteOffset,pixels.byteOffset+pixels.byteLength),frame={mac:s.mac,frame:s.frame,width:s.width,height:s.height,pixels:pixelBuffer,at:Date.now()};emit('bridge:frame',frame);emit('bridge:notice',`Frame received from ${s.mac}`);cacheFrame(frame).catch(()=>{});}
  function diagnostic(parts,start,at=Date.now()){if(parts.length<start+6||!(/^[0-9A-F]{8}$/.test(parts[start]))||!(/^\d+$/.test(parts[start+1])))return null;return{boot:parts[start],sequence:+parts[start+1],uptime:+parts[start+2],code:parts[start+3],mac:parts[start+4],detail:parts.slice(start+5).join(' '),at};}
  function updateRadioFromDiagnostic(event){if(!event||!['WIFI_RADIO','CHANNEL_CHANGE'].includes(event.code))return false;const match=new RegExp(`\\b${event.code==='CHANNEL_CHANGE'?'to':'channel'}=(\\d+)`).exec(event.detail),channel=match?+match[1]:0;if(channel<1||channel>13||network.radioChannel===channel)return false;network.radioChannel=channel;return true;}
  function handleLine(line){if(!line)return;const p=line.split(' ');if(p[0]==='READY'){const channel=+(/\bchannel=(\d+)/.exec(line)?.[1]||0);if(channel>=1&&channel<=13)network.radioChannel=channel;emit('bridge:notice',`Bridge ${p[2]||''} connected`);state();return;}if(p[0]==='EVENT'){const kind=p[1],mac=p[2];try{if(kind==='WIFI'){network.wifi=p[2];network.wifiDetail=p.slice(3).join(' ');state();emit('bridge:network-event',{service:'Wi-Fi',status:network.wifi,detail:network.wifiDetail});}
    else if(kind==='MQTT_STATUS'){network.mqtt=p[2];network.mqttDetail=p.slice(3).join(' ');state();emit('bridge:network-event',{service:'MQTT broker',status:network.mqtt,detail:network.mqttDetail});}
    else if(kind==='DIAG'){const d=diagnostic(p,2);if(d){if(updateRadioFromDiagnostic(d))state();emit('bridge:diagnostic',d);}}
    else if(kind==='SNAP_BEGIN')startSnapshot(p);
    else if(kind==='SNAP_DATA'&&snapshot)addSnapshot(p);
    else if(kind==='SNAP_END'&&snapshot){clearFrameRequest();if(p[3]==='timeout'){snapshot=null;emit('bridge:error','Frame transfer stalled or the camera went offline. Wait for it to reconnect, then try again.');}else finishSnapshot(p).catch(e=>emit('bridge:error',e.message));}
    else if(kind==='STATE'){const e={mac,id:+p[3],value:p[4],score:+p[5],frame:+p[6],at:Date.now()};states.set(`${mac}:${e.id}`,e);emit('bridge:state-event',e);}
    else if(kind==='CELL_STATE'){const e={mac,id:+p[3],value:p[4],score:+p[5],frame:+p[6],at:Date.now()};cellStates.set(`${mac}:${e.id}`,e);emit('bridge:cell-state-event',e);}
    else if(kind==='CELL_ANALYSIS'){const numbers=value=>value.split(',').map(Number);const e={mac,id:+p[3],frame:+p[4],score:+p[5],threshold:+p[6],referenceEdges:+p[7],liveEdges:+p[8],peakCount:+p[9],angles:numbers(p[10]),reference:numbers(p[11]),live:numbers(p[12]),at:Date.now()};if(e.angles.length!==10||e.reference.length!==31||e.live.length!==31||e.peakCount<0||e.peakCount>10||[e.id,e.frame,e.score,e.threshold,e.referenceEdges,e.liveEdges,...e.angles,...e.reference,...e.live].some(value=>!Number.isFinite(value)))throw Error('Invalid cell analysis from bridge');emit('bridge:cell-analysis',e);}
    else if(kind==='DISCOVER'||kind==='CONFIG_APPLIED'||kind==='CALIBRATION_APPLIED'){if(kind!=='CALIBRATION_APPLIED')emit('bridge:notice',kind==='DISCOVER'?`Camera ${mac} discovered`:`Camera ${mac} applied revision ${p[3]}`);refresh().catch(e=>emit('bridge:error',e.message));}
    else if(kind==='CONFIG_ERROR'&&p[3]==='5'){const reason={1:'The camera rejected the baseline request data.',2:'The camera has not applied its configuration yet, or a snapshot is still active. Save changes and wait for the camera revision to match.',3:'The camera ran out of memory.',4:'The camera could not capture or save the baseline. Check its LittleFS storage and camera serial log.',5:'The camera is busy; wait for the current operation to finish.'}[p[4]]||`Camera error code ${p[4]}`;emit('bridge:request-result',{mac,kind:'baseline',ok:false,reason,raw:line});}
    else if(kind==='TIMEOUT'&&p[3]==='5')emit('bridge:request-result',{mac,kind:'baseline',ok:false,reason:'The camera did not acknowledge the baseline request. Check that it is online and wait for any transfer to finish.',raw:line});
    else if(kind==='REQUEST_ACK'&&p[3]==='5')emit('bridge:request-result',{mac,kind:'baseline',ok:p[4]==='0',reason:p[4]==='0'?'The camera captured and saved a new baseline.':`Camera status ${p[4]}`,raw:line});
    else if(kind==='TIMEOUT'&&['2','3','4'].includes(p[3]))emit('bridge:request-result',{mac,kind:'config',ok:false,reason:`Saved on the bridge, but the camera did not acknowledge configuration step ${p[3]}. The bridge will retry when the camera announces itself again.`,raw:line});
    else if(kind==='CONFIG_ERROR'&&['2','3','4'].includes(p[3]))emit('bridge:request-result',{mac,kind:'config',ok:false,reason:`Saved on the bridge, but the camera rejected configuration step ${p[3]} with status ${p[4]}.`,raw:line});
    else if(kind==='TIMEOUT'&&p[3]==='6'){clearFrameRequest();snapshot=null;emit('bridge:error','The camera did not respond to the frame request. Check that it is online, then try again.');}
    else if(kind==='CONFIG_ERROR'&&p[3]==='6'){clearFrameRequest();snapshot=null;emit('bridge:error',p[4]==='5'?'Camera is still transferring a frame, or has not captured one yet. Wait for the transfer to finish and try again.':line);}
    else if(kind==='MQTT')emit('bridge:mqtt',{topic:p[2],value:p.slice(3).join(' '),at:Date.now()});
    else if(kind==='CAMERA'){if(p[3]==='offline'&&requestedFrameMac===mac){clearFrameRequest();snapshot=null;emit('bridge:error',`Camera ${mac} went offline before its frame arrived.`);}for(const [key,value] of states)if(value.mac===mac)states.set(key,{...value,value:'unknown',score:null,frame:null,at:Date.now()});for(const [key,value] of cellStates)if(value.mac===mac)cellStates.set(key,{...value,value:'unknown',score:null,frame:null,at:Date.now()});const c=cameras.get(mac);if(c&&p[3]==='offline'){c.online=false;c.fps=null;health.delete(mac);}state();}
    else if(kind==='HEALTH'){const c=cameras.get(mac);if(c){const fr=Number(p[4]),now=Date.now(),snapshotActive=p[7]==='1',prev=health.get(mac);c.fps=Number.isSafeInteger(fr)&&prev&&!snapshotActive&&!prev.snapshotActive&&fr>=prev.frame&&now-prev.at>=1000&&now-prev.at<=15000?Math.round((fr-prev.frame)*10000/(now-prev.at))/10:null;if(Number.isSafeInteger(fr))health.set(mac,{frame:fr,at:now,snapshotActive});c.baseline=p[6]==='1';c.snapshotActive=snapshotActive;c.online=true;state();}}
    else if(kind==='CONFIG_ERROR'||kind==='TIMEOUT')emit('bridge:error',line);
  }catch(e){snapshot=null;emit('bridge:error',e.message||String(e));}if(kind!=='SNAP_DATA')emit('bridge:event',line);return;}if(pending){if(p[0]==='OK'||p[0]==='ERR'){const x=pending;pending=null;clearTimeout(x.timer);p[0]==='ERR'?x.reject(Error(line)):x.resolve(x.rows);}else pending.rows.push(line);}}
  async function readForever(){const dec=new TextDecoder();try{while(port&&reader){const {value,done}=await reader.read();if(done)break;buffer+=dec.decode(value,{stream:true});if(buffer.length>200000){buffer='';emit('bridge:error','Serial line exceeded size limit');}let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);handleLine(line);}}}catch(e){if(port)emit('bridge:error',e.message||String(e));}finally{if(port){await disconnect();}}}
  async function refresh(){const rows=await run('LIST'),next=new Map(),previousCameras=new Map(cameras);for(const line of rows){const r=parseRow(line);if(r?.type==='camera')next.set(r.mac,{...r,fps:previousCameras.get(r.mac)?.fps??null,snapshotActive:previousCameras.get(r.mac)?.snapshotActive??false});}cameras.clear();next.forEach((v,k)=>cameras.set(k,v));for(const mac of health.keys())if(!cameras.has(mac))health.delete(mac);for(const mac of cameras.keys()){const cfg={revision:0,lastAutoSizeRevision:0,cells:[],topics:{},settings:{resolution:0,brightness:0,contrast:0,saturation:0,vflip:0,hmirror:0}};for(const line of await run(`GET ${mac}`)){const r=parseRow(line);if(r?.type==='config'){cfg.revision=r.revision;cfg.lastAutoSizeRevision=r.lastAutoSizeRevision;cfg.settings=r.settings;}else if(r?.type==='cell')cfg.cells.push(r.cell);else if(r?.type==='topic')cfg.topics[r.id]=r.name;}configs.set(mac,cfg);}for(const mac of configs.keys())if(!cameras.has(mac))configs.delete(mac);let sr;try{sr=await run('STATES');}catch(error){if(/ERR CAMERA unknown/.test(error.message))throw Error('Bridge firmware is too old for this app. Upload the updated Bridge_Controller.ino.');throw error;}const currentCells=new Set();for(const line of sr){const x=line.split(' ');if(x[0]==='OUTPUT'&&MAC.test(x[1])){const key=`${x[1]}:${x[2]}`,previous=states.get(key);states.set(key,{mac:x[1],id:+x[2],value:x[3],score:previous?.value===x[3]?previous.score:null,frame:previous?.value===x[3]?previous.frame:null,at:Date.now()});}else if(x[0]==='SENSOR'&&MAC.test(x[1])){const key=`${x[1]}:${x[2]}`,previous=cellStates.get(key);currentCells.add(key);cellStates.set(key,{mac:x[1],id:+x[2],value:x[3],score:previous?.value===x[3]?previous.score:null,frame:previous?.value===x[3]?previous.frame:null,at:Date.now()});}}for(const key of cellStates.keys())if(!currentCells.has(key))cellStates.delete(key);for(const line of await run('STATUS')){const x=line.split(' ');if(x[0]==='RADIO_STATUS'){network.radioChannel=+x[1];network.actualRadioChannel=+x[2];}else if(x[0]==='WIFI_STATUS'&&!(network.wifi==='failed'&&x[1]==='disconnected')){network.wifi=x[1];network.wifiDetail=x[2]==='-'?'':x.slice(2).join(' ');}else if(x[0]==='MQTT_STATUS'&&!(network.mqtt==='failed'&&x[1]==='disconnected')){network.mqtt=x[1];network.mqttDetail=x[2]||'';}else if(x[0]==='SAVED_SETTINGS'){network.wifiSaved=x[1]==='1';network.mqttSaved=x[2]==='1';}}state();return true;}
  async function connect(id){if(port)await disconnect();let p=portsById.get(id);if(!p){const ps=await navigator.serial.getPorts();ps.map(portInfo);p=portsById.get(id)||ps[0];}if(!p)throw Error('Choose a USB serial device first');try{await p.open({baudRate:115200});}catch(e){throw Error(/busy|access|permission/i.test(e.message)?'USB port is in use or permission was denied. Close other serial apps and try again.':e.message);}port=p;writer=port.writable.getWriter();reader=port.readable.getReader();buffer='';queue=Promise.resolve();readLoop=readForever();state();try{await refresh();}catch(e){await disconnect();throw Error(/Timed out: LIST/.test(e.message)?'The selected port did not answer as a Railway bridge.':e.message);}logs().catch(()=>{});refreshTimer=setInterval(()=>{if(!requestedFrameMac&&!snapshot)refresh().catch(e=>emit('bridge:error',e.message));},7000);}
  async function disconnect(){clearInterval(refreshTimer);refreshTimer=null;clearFrameRequest();snapshot=null;failPending('Bridge disconnected');const p=port;port=null;try{if(reader){await reader.cancel();reader.releaseLock();}}catch{}reader=null;try{if(writer){writer.releaseLock();}}catch{}writer=null;try{if(p?.readable||p?.writable)await p.close();}catch{}cameras.clear();configs.clear();states.clear();cellStates.clear();network={wifi:'disconnected',wifiDetail:'',mqtt:'disconnected',mqttDetail:'',wifiSaved:null,mqttSaved:null};state();}
  async function logs(){const rows=await run('LOG'),now=rows.find(line=>line.startsWith('LOG_NOW '))?.split(' '),bridgeUptime=now?+now[2]:0,wallNow=Date.now();for(const row of rows){if(row.startsWith('DIAG ')){const parts=row.split(' '),at=now&&parts[1]===now[1]?wallNow-((bridgeUptime-(+parts[3]))>>>0):wallNow,d=diagnostic(parts,1,at);if(d){if(updateRadioFromDiagnostic(d))state();emit('bridge:diagnostic',d);}}}return rows.length;}
  function validateConfig(config,otherIds=[]){const dims=[[320,240],[640,480],[800,600],[1024,768]],d=dims[config?.settings?.resolution],cells=config?.cells||[];if(!d)throw Error('Choose a valid resolution');if(cells.length>300)throw Error('Camera supports at most 300 sensors');const ids=new Set(),groups=new Set(),outputs=new Set(otherIds);for(const c of cells){if(!Number.isInteger(c.id)||c.id<1||c.id>2147483647||ids.has(c.id))throw Error('Sensor IDs must be unique positive numbers');ids.add(c.id);if(c.group)groups.add(c.group);if(!Number.isInteger(c.x)||c.x<0||c.x>=d[0]||!Number.isInteger(c.y)||c.y<0||c.y>=d[1])throw Error(`Sensor ${c.id} at ${c.x}, ${c.y} is outside the selected ${d[0]} × ${d[1]} image`);if(!Number.isInteger(c.radius)||c.radius<3||c.radius>50)throw Error('Sensor radius must be 3–50 px');if(![0,1].includes(c.shape))throw Error('Invalid sensor shape');if(c.floor<10||c.floor>500||c.tolerance<0||c.tolerance>20||!Number.isInteger(c.threshold)||c.threshold<50||c.threshold>1000||!Number.isInteger(c.enter)||c.enter<1||c.enter>255||!Number.isInteger(c.clear)||c.clear<1||c.clear>255||!Number.isInteger(c.createdRevision??0)||(c.createdRevision??0)<0)throw Error('Invalid sensor thresholds');}if(groups.size>64)throw Error('Camera supports at most 64 blocks');for(const c of cells){if(!c.group&&groups.has(c.id))throw Error('A sensor ID overlaps a block ID');const output=c.group||c.id;if(outputs.has(output))throw Error(`Output ID ${output} is already used by another camera`);}for(const [id,name] of Object.entries(config.topics||{}))if(!(/^[a-z0-9_-]{1,32}$/.test(name))||!cells.some(c=>(c.group||c.id)===+id))throw Error('Topic names must be 1–32 lowercase letters, digits, _ or -');const perOutput=new Map();for(const c of cells){const id=c.group||c.id;perOutput.set(id,config.topics?.[id]||String(id));}if(new Set(perOutput.values()).size!==perOutput.size)throw Error('Topic names must be unique');return true;}
  async function save(mac,config){if(!MAC.test(mac)||!configs.has(mac))throw Error('Unknown camera');const others=[...configs].filter(([id])=>id!==mac),otherIds=others.flatMap(([,c])=>c.cells.map(cell=>cell.group||cell.id));validateConfig(config,otherIds);const otherTopics=new Set(others.flatMap(([,c])=>[...new Set(c.cells.map(cell=>cell.group||cell.id))].map(id=>c.topics?.[id]||String(id))));for(const id of new Set(config.cells.map(cell=>cell.group||cell.id)))if(otherTopics.has(config.topics?.[id]||String(id)))throw Error(`Topic name for area ${id} is already used by another camera`);const current=configs.get(mac),s=config.settings;config.revision=current.revision;const cmds=[`BEGIN ${mac} ${config.revision+1} ${config.cells.length} ${s.resolution} ${s.brightness} ${s.contrast} ${s.saturation} ${s.vflip} ${s.hmirror}`,...config.cells.map((c,i)=>`CELL ${mac} ${i} ${c.id} ${c.group} ${c.x} ${c.y} ${c.radius} ${c.shape} ${c.floor} ${c.tolerance} ${c.threshold} ${c.enter} ${c.clear} ${c.createdRevision||0}`),`COMMIT ${mac}`,...[...new Set(config.cells.map(c=>c.group||c.id))].map(id=>`TOPIC ${mac} ${id} ${hex(config.topics?.[id]||String(id))}`)];for(const c of cmds)await run(c,30000);await refresh();return true;}
  async function cachedFrame(mac){try{const db=await frameDb(),saved=await new Promise((resolve,reject)=>{const transaction=db.transaction('frames','readonly'),request=transaction.objectStore('frames').get(mac);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);});if(saved)return{...saved,cached:true};}catch{}try{const legacy=JSON.parse(localStorage.getItem('frame:'+mac)||'null');if(!legacy)return null;const saved={...legacy,pixels:new Uint8Array(legacy.pixels).buffer};cacheFrame(saved).then(()=>localStorage.removeItem('frame:'+mac)).catch(()=>{});return{...saved,cached:true};}catch{return null;}}
  function stopMonitor(){if(monitorClient){monitorClient.end(true);monitorClient=null;}}
  async function monitorSave(settings){
    if(!window.mqtt?.connect)throw Error('The browser MQTT library could not be loaded. Check the internet connection and reload.');
    const clean={host:String(settings.host||'').trim(),port:+settings.port,root:String(settings.root||'').replace(/^\/+|\/+$/g,''),user:String(settings.user||''),password:String(settings.password||'')};
    if(!clean.host||!clean.root||!Number.isInteger(clean.port)||clean.port<1||clean.port>65535)throw Error('Enter a valid WebSocket broker host, port and topic root');
    localStorage.setItem('mqttViewer',JSON.stringify(clean));stopMonitor();emit('monitor:status',{status:'connecting',detail:'Connecting with MQTT over WebSockets…',settings:clean});
    const scheme=location.protocol==='https:'?'wss':'ws',url=/^wss?:\/\//i.test(clean.host)?clean.host:`${scheme}://${clean.host}:${clean.port}`;
    monitorClient=window.mqtt.connect(url,{username:clean.user||undefined,password:clean.password||undefined,reconnectPeriod:3000,connectTimeout:10000,clientId:`railway_web_${Math.random().toString(16).slice(2)}`});
    monitorClient.on('connect',()=>{monitorClient.subscribe(`${clean.root}/areas/+/state`,{qos:0});monitorClient.subscribe(`${clean.root}/controller/health`,{qos:0});emit('monitor:status',{status:'connected',detail:`Subscribed through ${url}`,settings:clean,bridgeOnline:null});});
    monitorClient.on('reconnect',()=>emit('monitor:status',{status:'connecting',detail:'Reconnecting to MQTT WebSocket…',settings:clean}));
    monitorClient.on('error',error=>emit('monitor:status',{status:'error',detail:error.message,settings:clean}));
    monitorClient.on('close',()=>emit('monitor:status',{status:'disconnected',detail:'MQTT WebSocket disconnected.',settings:clean}));
    monitorClient.on('message',(topic,payload,packet)=>{const value=payload.toString();if(topic===`${clean.root}/controller/health`){emit('monitor:status',{status:'connected',detail:`Subscribed through ${url}`,settings:clean,bridgeOnline:value!=='offline'});return;}const prefix=`${clean.root}/areas/`;if(!topic.startsWith(prefix)||!topic.endsWith('/state'))return;const name=topic.slice(prefix.length,-6);if(!value){emit('monitor:removed',{topic,name});return;}if(!['clear','occupied','unknown'].includes(value))return;emit('monitor:message',{topic,name,value,retained:!!packet.retain,at:Date.now()});});
    return true;
  }
  async function monitorForget(){stopMonitor();localStorage.removeItem('mqttViewer');emit('monitor:status',{status:'disconnected',detail:'Viewer settings removed.'});}
  async function requestFrame(mac){if(!MAC.test(mac))throw Error('Invalid camera');expectFrame(mac);try{const result=await run(`FRAME ${mac}`,12000);if(requestedFrameMac===mac&&!snapshot)emit('bridge:progress',{mac,received:0,total:1});return result;}catch(error){clearFrameRequest();throw error;}}
  function requestBaseline(mac){if(!MAC.test(mac))throw Error('Invalid camera');return run(`BASELINE ${mac}`,12000);}
  function requestCalibration(mac,mode='new'){if(!MAC.test(mac)||!['new','all'].includes(mode))throw Error('Invalid calibration request');return run(`CALIBRATE ${mac} ${mode}`,12000);}
  function requestAnalysis(mac,id){if(!MAC.test(mac)||!Number.isInteger(id)||id<1)throw Error('Invalid sensor');return run(`ANALYSIS ${mac} ${id}`);}
  window.bridge={webSerial:true,ports:listPorts,choosePort,connect,disconnect,refresh,logs,frame:requestFrame,cachedFrame,baseline:requestBaseline,calibrate:requestCalibration,analysis:requestAnalysis,save,wifi:(s,p)=>run(`WIFI ${hex(s)} ${hex(p)}`),mqtt:(h,p,r,u,pw)=>run(`MQTT ${hex(h)} ${p} ${hex(r)} ${hex(u)} ${hex(pw)}`),forgetWifi:()=>run('FORGET_WIFI'),forgetMqtt:()=>run('FORGET_MQTT'),monitorSave,monitorForget,on:(name,cb)=>{const a=listeners.get(name)||[];a.push(cb);listeners.set(name,a);return()=>listeners.set(name,(listeners.get(name)||[]).filter(x=>x!==cb));}};
  window.addEventListener('load',()=>{try{const s=JSON.parse(localStorage.getItem('mqttViewer')||'null');if(s)monitorSave(s).catch(error=>emit('monitor:status',{status:'error',detail:error.message,settings:s}));}catch{}state();});
})();
