'use strict';
(() => {
  const listeners = new Map();
  const emit = (name, data) => (listeners.get(name) || []).forEach(fn => { try { fn(data); } catch(e) { console.error(e); } });
  const MAC=/^[0-9A-F]{2}(?::[0-9A-F]{2}){5}$/;
  const portsById = new Map(); let port, reader, writer, readLoop, refreshTimer, buffer=''; let pending=null; let queue=Promise.resolve();
  const cameras=new Map(), configs=new Map(), states=new Map(), cellStates=new Map();
  let network={wifi:'disconnected',wifiDetail:'',mqtt:'disconnected',mqttDetail:'',wifiSaved:null,mqttSaved:null}; let snapshot=null;
  const health=new Map(); let monitorClient=null;
  function hex(s=''){const bytes=new TextEncoder().encode(String(s));return bytes.length?[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase():'-';}
  function portInfo(p, i){const info=p.getInfo?.()||{};const id=`webserial:${info.usbVendorId||0}:${info.usbProductId||0}:${i}`;portsById.set(id,p);return {path:id,manufacturer:info.usbVendorId===0x303a?'Espressif':'USB serial',vendorId:(info.usbVendorId||0).toString(16).padStart(4,'0'),productId:(info.usbProductId||0).toString(16).padStart(4,'0')};}
  async function listPorts(){if(!navigator.serial)throw Error('Web Serial is not supported in this browser. Use Chrome or Edge on desktop.'); const ps=await navigator.serial.getPorts();portsById.clear();return ps.map(portInfo);}
  async function choosePort(){if(!navigator.serial)throw Error('Web Serial is not supported in this browser.');const p=await navigator.serial.requestPort();const ps=await navigator.serial.getPorts();portsById.clear();const list=ps.map(portInfo);return list;}
  function state(){emit('bridge:state',{connected:!!port,path:port?'Web Serial · 115200 baud':'',cameras:[...cameras.values()],configs:Object.fromEntries(configs),states:Object.fromEntries(states),cellStates:Object.fromEntries(cellStates),network:{...network}});}
  function failPending(message){if(pending){clearTimeout(pending.timer);pending.reject(Error(message));pending=null;}}
  async function run(command, timeout=12000){const task=queue.catch(()=>{}).then(()=>new Promise(async(resolve,reject)=>{if(!writer)return reject(Error('Connect a bridge first'));pending={rows:[],resolve,reject,timer:setTimeout(()=>failPending(`Timed out: ${command.split(' ')[0]}`),timeout)};try{await writer.write(new TextEncoder().encode(command+'\n'));}catch(e){failPending(e.message||String(e));}}));queue=task;return task;}
  function parseRow(line){const p=line.trim().split(/\s+/);if(p[0]==='CAMERA'&&MAC.test(p[1]))return{type:'camera',mac:p[1],online:p[2]==='online',revision:+p[3],remoteRevision:+p[4],count:+p[5],baseline:p[6]==='1'};if(p[0]==='CONFIG'&&MAC.test(p[1]))return{type:'config',revision:+p[2],lastAutoSizeRevision:+p[4],settings:{resolution:+p[5],brightness:+p[6],contrast:+p[7],saturation:+p[8],vflip:+p[9],hmirror:+p[10]}};if(p[0]==='CELL')return{type:'cell',cell:{id:+p[2],group:+p[3],x:+p[4],y:+p[5],radius:+p[6],shape:+p[7],floor:+p[8],tolerance:+p[9],threshold:+p[10],enter:+p[11],clear:+p[12],createdRevision:+p[13]}};if(p[0]==='TOPIC')return{type:'topic',id:+p[1],name:p[2]};}
  function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let n=0;n<8;n++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
  let frameDbPromise;
  function frameDb(){if(!frameDbPromise)frameDbPromise=new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('IndexedDB is unavailable'));const request=indexedDB.open('railway-camera-frames',1);request.onupgradeneeded=()=>request.result.createObjectStore('frames',{keyPath:'mac'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('Could not open frame cache'));});return frameDbPromise;}
  async function cacheFrame(frame){const db=await frameDb();await new Promise((resolve,reject)=>{const transaction=db.transaction('frames','readwrite');transaction.objectStore('frames').put(frame);transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error||Error('Could not cache frame'));});}
  async function finishSnapshot(parts){const s=snapshot;snapshot=null;if(!s||parts[2]!==s.mac||parts[3]!=='ok'||s.offset!==s.count||crc32(s.wire)!==s.wireCrc)throw Error('Frame failed transfer CRC or length check');let pixels=s.wire;if(s.codec===1){if(typeof DecompressionStream==='undefined')throw Error('Compressed frame received but this browser cannot decompress it');const ds=new DecompressionStream('deflate-raw');const ab=await new Response(new Blob([s.wire]).stream().pipeThrough(ds)).arrayBuffer();pixels=new Uint8Array(ab);}if(pixels.length!==s.rawCount||crc32(pixels)!==s.crc)throw Error('Frame failed image CRC or length check');const pixelBuffer=pixels.buffer.slice(pixels.byteOffset,pixels.byteOffset+pixels.byteLength),frame={mac:s.mac,frame:s.frame,width:s.width,height:s.height,pixels:pixelBuffer,at:Date.now()};emit('bridge:frame',frame);emit('bridge:notice',`Frame received from ${s.mac}`);cacheFrame(frame).catch(()=>{});}
  function diagnostic(parts,start,at=Date.now()){if(parts.length<start+6)return null;return{boot:parts[start],sequence:+parts[start+1],uptime:+parts[start+2],code:parts[start+3],mac:parts[start+4],detail:parts.slice(start+5).join(' '),at};}
  function handleLine(line){if(!line)return;const p=line.split(' ');if(p[0]==='READY'){emit('bridge:notice',`Bridge ${p[2]||''} connected`);state();return;}if(p[0]==='EVENT'){const kind=p[1],mac=p[2];try{if(kind==='WIFI'){network.wifi=p[2];network.wifiDetail=p.slice(3).join(' ');state();emit('bridge:network-event',{service:'Wi-Fi',status:network.wifi,detail:network.wifiDetail});}
    else if(kind==='MQTT_STATUS'){network.mqtt=p[2];network.mqttDetail=p.slice(3).join(' ');state();emit('bridge:network-event',{service:'MQTT broker',status:network.mqtt,detail:network.mqttDetail});}
    else if(kind==='DIAG'){const d=diagnostic(p,2);if(d)emit('bridge:diagnostic',d);}
    else if(kind==='SNAP_BEGIN'){const rawCount=+p[6], count=p[8]===undefined?rawCount:+p[8];snapshot={mac,frame:+p[3],width:+p[4],height:+p[5],rawCount,crc:parseInt(p[7],16)>>>0,count,wireCrc:p[9]===undefined?(parseInt(p[7],16)>>>0):(parseInt(p[9],16)>>>0),codec:p[10]===undefined?0:+p[10],offset:0,wire:new Uint8Array(count)};emit('bridge:progress',{mac,received:0,total:count});}
    else if(kind==='SNAP_DATA'&&snapshot){const offset=+p[3],hexdata=p[4]||'';if(offset!==snapshot.offset)throw Error('Frame chunk is out of order');const bytes=new Uint8Array(hexdata.length/2);for(let i=0;i<bytes.length;i++)bytes[i]=parseInt(hexdata.slice(i*2,i*2+2),16);snapshot.wire.set(bytes,offset);snapshot.offset+=bytes.length;emit('bridge:progress',{mac,received:snapshot.offset,total:snapshot.count});}
    else if(kind==='SNAP_END'&&snapshot){finishSnapshot(p).catch(e=>emit('bridge:error',e.message));}
    else if(kind==='STATE'){const e={mac,id:+p[3],value:p[4],score:+p[5],frame:+p[6],at:Date.now()};states.set(`${mac}:${e.id}`,e);emit('bridge:state-event',e);}
    else if(kind==='CELL_STATE'){const e={mac,id:+p[3],value:p[4],score:+p[5],frame:+p[6],at:Date.now()};cellStates.set(`${mac}:${e.id}`,e);emit('bridge:cell-state-event',e);}
    else if(kind==='CELL_ANALYSIS'){const numbers=value=>value.split(',').map(Number);const e={mac,id:+p[3],frame:+p[4],score:+p[5],threshold:+p[6],referenceEdges:+p[7],liveEdges:+p[8],peakCount:+p[9],angles:numbers(p[10]),reference:numbers(p[11]),live:numbers(p[12]),at:Date.now()};if(e.angles.length!==10||e.reference.length!==31||e.live.length!==31)throw Error('Invalid cell analysis from bridge');emit('bridge:cell-analysis',e);}
    else if(kind==='DISCOVER'||kind==='CONFIG_APPLIED'||kind==='CALIBRATION_APPLIED'){if(kind!=='CALIBRATION_APPLIED')emit('bridge:notice',kind==='DISCOVER'?`Camera ${mac} discovered`:`Camera ${mac} applied revision ${p[3]}`);refresh().catch(e=>emit('bridge:error',e.message));}
    else if(kind==='REQUEST_ACK'&&p[3]==='5')emit('bridge:request-result',{mac,kind:'baseline',ok:p[4]==='0',reason:p[4]==='0'?'The camera captured and saved a new baseline.':`Camera status ${p[4]}`,raw:line});
    else if(kind==='MQTT')emit('bridge:mqtt',{topic:p[2],value:p.slice(3).join(' '),at:Date.now()});
    else if(kind==='CAMERA'){const c=cameras.get(mac);if(c&&p[3]==='offline'){c.online=false;c.fps=null;}state();}
    else if(kind==='HEALTH'){const c=cameras.get(mac);if(c){const fr=+p[4],now=Date.now(),prev=health.get(mac);c.fps=prev&&now-prev.at>=1000&&now-prev.at<=15000?Math.round((fr-prev.frame)*10000/(now-prev.at))/10:null;health.set(mac,{frame:fr,at:now});c.baseline=p[6]==='1';c.snapshotActive=p[7]==='1';c.online=true;state();}}
  }catch(e){emit('bridge:error',e.message||String(e));}emit('bridge:event',line);return;}if(pending){if(p[0]==='OK'||p[0]==='ERR'){const x=pending;pending=null;clearTimeout(x.timer);p[0]==='ERR'?x.reject(Error(line)):x.resolve(x.rows);}else pending.rows.push(line);}}
  async function readForever(){const dec=new TextDecoder();try{while(port&&reader){const {value,done}=await reader.read();if(done)break;buffer+=dec.decode(value,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);handleLine(line);}}}catch(e){if(port)emit('bridge:error',e.message||String(e));}finally{if(port){await disconnect();}}}
  async function refresh(){const rows=await run('LIST');const next=new Map();for(const line of rows){const r=parseRow(line);if(r?.type==='camera')next.set(r.mac,{...r,fps:cameras.get(r.mac)?.fps??null,snapshotActive:cameras.get(r.mac)?.snapshotActive??false});}cameras.clear();next.forEach((v,k)=>cameras.set(k,v));for(const mac of cameras.keys()){const cfg={revision:0,cells:[],topics:{},settings:{resolution:0,brightness:0,contrast:0,saturation:0,vflip:0,hmirror:0}};for(const line of await run(`GET ${mac}`)){const r=parseRow(line);if(r?.type==='config'){cfg.revision=r.revision;cfg.settings=r.settings;}else if(r?.type==='cell')cfg.cells.push(r.cell);else if(r?.type==='topic')cfg.topics[r.id]=r.name;}configs.set(mac,cfg);}const sr=await run('STATES');for(const line of sr){const x=line.split(' ');if(x[0]==='OUTPUT'&&MAC.test(x[1]))states.set(`${x[1]}:${x[2]}`,{mac:x[1],id:+x[2],value:x[3],at:Date.now()});if(x[0]==='SENSOR'&&MAC.test(x[1]))cellStates.set(`${x[1]}:${x[2]}`,{mac:x[1],id:+x[2],value:x[3],at:Date.now()});}for(const line of await run('STATUS')){const x=line.split(' ');if(x[0]==='RADIO_STATUS'){network.radioChannel=+x[1];network.actualRadioChannel=+x[2];}else if(x[0]==='WIFI_STATUS'){network.wifi=x[1];network.wifiDetail=x[2]==='-'?'':x.slice(2).join(' ');}else if(x[0]==='MQTT_STATUS'){network.mqtt=x[1];network.mqttDetail=x[2]||'';}else if(x[0]==='SAVED_SETTINGS'){network.wifiSaved=x[1]==='1';network.mqttSaved=x[2]==='1';}}state();return true;}
  async function connect(id){if(port)await disconnect();let p=portsById.get(id);if(!p){const ps=await navigator.serial.getPorts();const list=ps.map(portInfo);p=portsById.get(id)||ps[0];}if(!p)throw Error('Choose a USB serial device first');try{await p.open({baudRate:115200});}catch(e){throw Error(/busy|access|permission/i.test(e.message)?'USB port is in use or permission was denied. Close other serial apps and try again.':e.message);}port=p;writer=port.writable.getWriter();reader=port.readable.getReader();buffer='';readLoop=readForever();state();try{await refresh();}catch(e){await disconnect();throw Error(/Timed out: LIST/.test(e.message)?'The selected port did not answer as a Railway bridge.':e.message);}refreshTimer=setInterval(()=>refresh().catch(e=>emit('bridge:error',e.message)),7000);logs().catch(()=>{});}
  async function disconnect(){clearInterval(refreshTimer);refreshTimer=null;failPending('Bridge disconnected');const p=port;port=null;try{if(reader){await reader.cancel();reader.releaseLock();}}catch{}reader=null;try{if(writer){writer.releaseLock();}}catch{}writer=null;try{if(p?.readable||p?.writable)await p.close();}catch{}cameras.clear();configs.clear();states.clear();cellStates.clear();network={wifi:'disconnected',wifiDetail:'',mqtt:'disconnected',mqttDetail:'',wifiSaved:null,mqttSaved:null};state();}
  async function logs(){const rows=await run('LOG');for(const row of rows){if(row.startsWith('DIAG ')){const d=diagnostic(row.split(' '),1);if(d)emit('bridge:diagnostic',d);}}return rows.length;}
  function validateConfig(config){const dims=[[320,240],[640,480],[800,600],[1024,768]],d=dims[config?.settings?.resolution];if(!d)throw Error('Choose a valid resolution');if((config.cells||[]).length>300)throw Error('Camera supports at most 300 sensors');const ids=new Set();for(const c of config.cells||[]){if(ids.has(c.id))throw Error('Sensor IDs must be unique');ids.add(c.id);if(c.x<0||c.x>=d[0]||c.y<0||c.y>=d[1])throw Error(`Sensor ${c.id} is outside the selected image`);}return true;}
  async function save(mac,config){if(!MAC.test(mac)||!configs.has(mac))throw Error('Unknown camera');validateConfig(config);const current=configs.get(mac);const s=config.settings;config.revision=current.revision;const cmds=[`BEGIN ${mac} ${config.revision+1} ${config.cells.length} ${s.resolution} ${s.brightness} ${s.contrast} ${s.saturation} ${s.vflip} ${s.hmirror}`,...config.cells.map((c,i)=>`CELL ${mac} ${i} ${c.id} ${c.group} ${c.x} ${c.y} ${c.radius} ${c.shape} ${c.floor} ${c.tolerance} ${c.threshold} ${c.enter} ${c.clear} ${c.createdRevision||0}`),`COMMIT ${mac}`,...[...new Set(config.cells.map(c=>c.group||c.id))].map(id=>`TOPIC ${mac} ${id} ${hex(config.topics?.[id]||String(id))}`)];for(const c of cmds)await run(c,30000);await refresh();return true;}
  async function cachedFrame(mac){try{const db=await frameDb(),saved=await new Promise((resolve,reject)=>{const transaction=db.transaction('frames','readonly'),request=transaction.objectStore('frames').get(mac);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);});if(saved)return{...saved,cached:true};}catch{}try{const legacy=JSON.parse(localStorage.getItem('frame:'+mac)||'null');if(!legacy)return null;const saved={...legacy,pixels:new Uint8Array(legacy.pixels).buffer};cacheFrame(saved).then(()=>localStorage.removeItem('frame:'+mac)).catch(()=>{});return{...saved,cached:true};}catch{return null;}}
  function stopMonitor(){if(monitorClient){monitorClient.end(true);monitorClient=null;}}
  async function monitorSave(settings){
    if(!window.mqtt?.connect)throw Error('The browser MQTT library could not be loaded. Check the internet connection and reload.');
    const clean={host:String(settings.host||'').trim(),port:+settings.port,root:String(settings.root||'').replace(/^\/+|\/+$/g,''),user:String(settings.user||''),password:String(settings.password||'')};
    if(!clean.host||!clean.root||!Number.isInteger(clean.port)||clean.port<1||clean.port>65535)throw Error('Enter a valid WebSocket broker host, port and topic root');
    localStorage.setItem('mqttViewer',JSON.stringify(clean));stopMonitor();emit('monitor:status',{status:'connecting',detail:'Connecting with MQTT over WebSockets…',settings:clean});
    const scheme=location.protocol==='https:'?'wss':'ws',url=/^wss?:\/\//i.test(clean.host)?clean.host:`${scheme}://${clean.host}:${clean.port}`;
    monitorClient=window.mqtt.connect(url,{username:clean.user||undefined,password:clean.password||undefined,reconnectPeriod:3000,connectTimeout:10000,clientId:`railway_web_${Math.random().toString(16).slice(2)}`});
    monitorClient.on('connect',()=>{monitorClient.subscribe(`${clean.root}/areas/+/state`,{qos:0});monitorClient.subscribe(`${clean.root}/controller/health`,{qos:0});emit('monitor:status',{status:'connected',detail:`Subscribed through ${url}`,settings:clean,bridgeOnline:null});});
    monitorClient.on('reconnect',()=>emit('monitor:status',{status:'connecting',detail:'Reconnecting to MQTT WebSocket…',settings:clean}));
    monitorClient.on('error',error=>emit('monitor:status',{status:'error',detail:error.message,settings:clean}));
    monitorClient.on('close',()=>emit('monitor:status',{status:'disconnected',detail:'MQTT WebSocket disconnected.',settings:clean}));
    monitorClient.on('message',(topic,payload,packet)=>{const value=payload.toString();if(topic===`${clean.root}/controller/health`){emit('monitor:status',{status:'connected',detail:`Subscribed through ${url}`,settings:clean,bridgeOnline:value!=='offline'});return;}const prefix=`${clean.root}/areas/`;if(!topic.startsWith(prefix)||!topic.endsWith('/state'))return;const name=topic.slice(prefix.length,-6);if(!value){emit('monitor:removed',{topic,name});return;}if(!['clear','occupied','unknown'].includes(value))return;emit('monitor:message',{topic,name,value,retained:!!packet.retain,at:Date.now()});});
    return true;
  }
  async function monitorForget(){stopMonitor();localStorage.removeItem('mqttViewer');emit('monitor:status',{status:'disconnected',detail:'Viewer settings removed.'});}
  window.bridge={webSerial:true,ports:listPorts,choosePort,connect,disconnect,refresh,logs,frame:mac=>run(`FRAME ${mac}`,12000),cachedFrame,baseline:mac=>run(`BASELINE ${mac}`,12000),calibrate:(mac,mode='new')=>run(`CALIBRATE ${mac} ${mode}`,12000),analysis:(mac,id)=>run(`ANALYSIS ${mac} ${id}`),save,wifi:(s,p)=>run(`WIFI ${hex(s)} ${hex(p)}`),mqtt:(h,p,r,u,pw)=>run(`MQTT ${hex(h)} ${p} ${hex(r)} ${hex(u)} ${hex(pw)}`),forgetWifi:()=>run('FORGET_WIFI'),forgetMqtt:()=>run('FORGET_MQTT'),monitorSave,monitorForget,on:(name,cb)=>{const a=listeners.get(name)||[];a.push(cb);listeners.set(name,a);return()=>listeners.set(name,(listeners.get(name)||[]).filter(x=>x!==cb));}};
  window.addEventListener('load',()=>{try{const s=JSON.parse(localStorage.getItem('mqttViewer')||'null');if(s)monitorSave(s).catch(error=>emit('monitor:status',{status:'error',detail:error.message,settings:s}));}catch{}state();});
})();
