(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  else root.SensorTest=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const MIN_MIDDLE_ANGLE=120,TRAVERSAL_MS=30000,EVENT_SLOP_MS=1000;
  function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
  function angleAt(a,m,b){const ax=a.x-m.x,ay=a.y-m.y,bx=b.x-m.x,by=b.y-m.y,lengths=Math.hypot(ax,ay)*Math.hypot(bx,by);if(!lengths)return 0;return Math.acos(Math.max(-1,Math.min(1,(ax*bx+ay*by)/lengths)))*180/Math.PI;}
  function candidates(cells,block=0){const groups=new Map();for(const cell of cells||[])if(cell.group&&(!block||cell.group===block)){if(!groups.has(cell.group))groups.set(cell.group,[]);groups.get(cell.group).push(cell);}const result=[];for(const [group,members] of groups)if(members.length>=3)for(const cell of members){const nearest=members.filter(other=>other.id!==cell.id).sort((a,b)=>distance(cell,a)-distance(cell,b)).slice(0,2),angle=nearest.length===2?angleAt(nearest[0],cell,nearest[1]):0;if(angle>=MIN_MIDDLE_ANGLE)result.push({id:cell.id,group,neighbors:nearest.map(item=>item.id),angle});}return result;}
  function create(cells,block=0){const tested=candidates(cells,block),bySensor=new Map(),results=new Map();for(const item of tested){results.set(item.id,{...item,passes:0,misses:0,maxScore:null,pending:null,lastAt:0});for(const id of [item.id,...item.neighbors]){if(!bySensor.has(id))bySensor.set(id,[]);bySensor.get(id).push(item.id);}}function ingest(event,isTransition=true){const affected=bySensor.get(event.id)||[],at=Number.isFinite(event.at)?event.at:Date.now();for(const id of affected){const result=results.get(id);if(event.id===id&&Number.isFinite(event.score))result.maxScore=result.maxScore===null?event.score:Math.max(result.maxScore,event.score);if(!isTransition||event.value!=='occupied')continue;if(event.id===id){result.lastAt=at;if(result.pending&&at>=result.pending.at-EVENT_SLOP_MS)result.pending.hit=true;continue;}const side=result.neighbors.indexOf(event.id);if(side<0)continue;const recentMiddle=result.lastAt&&at-result.lastAt<=EVENT_SLOP_MS;if(!result.pending||at-result.pending.at>TRAVERSAL_MS){result.pending={side,at,hit:recentMiddle};continue;}if(result.pending.side===side){result.pending={side,at,hit:recentMiddle};continue;}if(result.pending.hit||recentMiddle)result.passes++;else result.misses++;result.pending=null;result.lastAt=0;}}function summary(){return[...results.values()].map(({pending,lastAt,...item})=>item).sort((a,b)=>a.group-b.group||a.id-b.id);}return{ingest,summary,candidateCount:tested.length};}
  return{angleAt,candidates,create,MIN_MIDDLE_ANGLE,TRAVERSAL_MS};
});
